### ISSUE TITLE
Newmark Controller for translation stages with Arcus

### ISSUE THREAD

**Issue by bws5** [AlexShkarin/pyLabLib-v0#4]
Hello,

I am trying to use pyLabLib with the Arcus module for a Newmark controller/translation stages: Newmark uses the Arcus .dlls, so I am hoping that this is not as much of a stretch as it sounds. Additionally, they are both Performax modules that employ nearly identical ascii commands, and they have similar default device names (the [Arcus's is 4EX00](http://www.zilvertron.com/media/arcus/PMX_4EX_SA.pdf) whereas [the Newmark that we have is  2ED00](https://www.newmarksystems.com/downloads/software/NSC-A/NSC-A2L/NSC-A2L_Manual_Rev_1.18.pdf)) 

Using pyvisa (and communicating via USB-to-RS-485), I have been able to send commands to the translation stages in interactive mode (using the ascii commands that begin with the @00 address). Looking at the Arcus.py file in the devices directory, I've tried using both GenericPerformaxStage and Performax4EXStage for the device name: e.g.,

`with Arcus.Performax4EXStage('COM4') as stages:`

It doesn't balk at either name but I am getting the error, "Additional required library: SiUSBXp.dll". 

I have put both dll files in the aux_libs\devices\libs\x64 directory, but that error doesn't change. Is that the only place I need to have the dlls (or should I try putting them in the win32 location)? Lastly, other than the two dlls, do I need to install anything else for basic functionality? 

Thanks for any help you can give!

Ben

**Comment by AlexShkarin** [comment]
Hi Ben!

I don't have experience with RS-485 communication, only with the USB using the driver and the DLL. As far as I could see in the manual, the stage accepts both USB and RS-485. If you use USB, you need to install the appropriate drivers. For Arcus they are included in [Arcus Drivers and Tools](https://www.arcus-technology.com/support/downloads/download-info/drivers-and-tools-installer/), [Performax Series Installer](https://www.arcus-technology.com/support/downloads/download-info/performax-series-installer/) and [Performax USB Setup](https://www.arcus-technology.com/support/downloads/download-info/performax-usb-setup/) (all obtained at [Arcus website](https://www.arcus-technology.com/support/downloads/)); I'm not sure if all 3 are necessary, but they seem to be sufficient. Once the appropriate USB drivers are installed, one can connect the device directly via its USB port and use the [DLL](https://www.arcus-technology.com/support/downloads/download-info/usb-64-bit-dll/) to communicate with the device. To communicate via RS-485, one needs, as you described, a USB to RS-485 converter and a compatible software, after which you can just use their text protocol.

The code only communicates using DLL, and the path to the DLL is the argument of the class. That is why it shows the DLL loading error: it looks for a file named ``"COM4"`` but, of course, can not find it.

Thus, I can see two solutions. First, you can use the USB connectivity after installing the appropriate drivers, as described above. The DLL placement that you've named seems appropriate, as long as your Python interpreter is 64 bit (if you're not sure, you can see it when you run it in the command line); you can also place both DLLs in the same folder as your script, it should work as well. If the DLLs are in either of these places, you don't need to provide any path at all, but might need to give an ``idx`` argument, if you have more than one controller connected. To check how many devices you have, you can call ``Arcus.GenericPerformaxStage.get_devices_num()``; ideally, it will show something larger than 0.

Alternatively, I can rewrite the class to also accept a COM port and use serial communication. Provided that the command syntax is the same for the RS-485 and the USB modes, it shouldn't take much time. On the other hand, I won't have any way to test it, so it might have some bugs.

Let me know if you have further questions,

Alexey.

**Comment by bws5** [comment]
Hi Alexey–just getting back to this after a few weeks. The USB connection works (in he below, I've named the device "stages"). So stages.get_full_info() returns the device id 2ed00. 

However, stages.get_settings returns an empty object. I have tried a few variations on the ASCII commands (shorn of the @00 address described in my first comment). I've tried using those as arguments for the apply_sertings command. E g., stages.apply_sertings('JY+') to jog the y axis. That's not working (and also looks very different from the commands in the sample coffee you provided for the Andor camera).

Can you provide an example or two of what the Arcus commands look like? I assume there's a pattern that would allow us to extrapolate from the ASCII commands?

Thanks for the help!

Ben

**Comment by AlexShkarin** [comment]
Hi Ben,

Thank you for the update!

You're right, the bare ``Arcus.GenericPerformaxStage`` class only includes the most basic functionality for sending commands and parsing replies, but not much else. I have added it when I learned that different Arcus stages have very different sets of commands. This way, users have at least some starting point to communicate with their stages without having to write the DLL wrapping code by themselves. However, since I only have access to 4EX stage, that is the only one which is included in the library (it's hard to gaurantee working code on other stages without explicitly testing it, since sometimes the communication interfaces are not very well documented).

I'm sorry for the possible confusion.

Alexey.

**Comment by bws5** [comment]
Thanks Alexey—good to know that there's not something else that I was missing.

Ben

**Comment by bws5** [comment]
Hi Alexey, another update: you were right to be cautious about different definitions. Most of the definitions appear to be the same for the Newmark stage as for the Performax. However, the command to change the motor speed is slightly different (HSPD instead of HS: you can see [this on page 51 of the Newmark manual](https://www.newmarksystems.com/downloads/software/NSC-A/NSC-A2L/NSC-A2L_Manual_Rev_1.18.pdf)). I tried changing HS to HSPD in the aux file but in the error message, but even after I save those changes (and they show up in the debug readout), HS is still being passed as the argument (ValueError: '?HS'). Because HS is involved in get_settings() and get_full_status() I receive the '?HS' error for those as well. Do you have any suggestions for how I might approach this issue?

Thanks again,

Ben

**Comment by AlexShkarin** [comment]
Hi Ben,

That's strange, that file (``aux_libs.device.Arcus.py``) is the only place with the relevant code. Just in case: there are 4 methods which reference this command: ``get_speed``, ``get_axis_speed``, ``set_speed``, and ``set_axis_speed``. To make it work, you need to change ``HS`` to ``HSPD`` everywhere. After that, it should work fine.

There's a couple of other potential incompatibilities between the controllers that I noticed, mostly related to the different number of axes (2 axes ``XY`` for Newmark instead of 4 axes ``XYZU``). Here's the updated class code (it's still called ``Performax4EXStage`` for compatiblity, but if you like, you can add it to ``Arcus.py`` under a different name):
```python
class Performax4EXStage(GenericPerformaxStage):
    """
    Arcus Performax 4EX translation stage.

    Args:
        lib_path(str): path to the PerformaxCom.dll (default is to use the library supplied with the package)
        idx(int): stage index
    """
    def __init__(self, lib_path=None, idx=0):
        GenericPerformaxStage.__init__(self,lib_path=lib_path,idx=idx)
        self.set_absolute_mode()
        self.enable_all_outputs()
        self.ignore_limit_errors()
        self._add_settings_node("ignore_limit_errors",self.is_ignoring_limit_errors,self.ignore_limit_errors)
        self._add_status_node("positions",self.get_position,mux=("XY",))
        self._add_settings_node("global_speed",self.get_speed,self.set_speed)
        self._add_settings_node("axis_speed",self.get_axis_speed,self.set_axis_speed,mux=("XY",0))
        self._add_status_node("axis_status",self.get_status,mux=("XY",0))
        self._add_status_node("moving",self.is_moving,mux=("XY",0))

    @staticmethod
    def _check_axis(axis):
        if axis.lower() not in "xy":
            raise ArcusError("unrecognized axis: {}".format(axis))
        return axis.upper()

    def set_absolute_mode(self):
        """Set absolute motion mode"""
        self.query("ABS")
    def ignore_limit_errors(self, do_ignore=True):
        """
        Switch ignoring limit errors on or off.

        If on, limit error on one axis doesn't stop other axes.
        """
        self.query("IERR={}".format("1" if do_ignore else "0"))
    def is_ignoring_limit_errors(self):
        """
        Check if ignoring limit errors is on.

        If on, limit error on one axis doesn't stop other axes.
        """
        return self.query("IERR")=="1"
    def enable_output(self, axis, enable=True):
        """
        Enable axis output.

        If the output is disabled, the steps are generated by the controller, but not sent to the motors.
        """
        axis=self._check_axis(axis)
        axisn="XY".index(axis)+1
        self.query("EO{}={}".format(axisn,"1" if enable else "0"))
    def enable_all_outputs(self, enable=True):
        """Enable output on all axes"""
        self.query("EO={}".format("3" if enable else "0"))
        for axis in "XY":
            self.enable_output(axis,enable=enable)

    def get_position(self, axis):
        """Get the current axis position"""
        axis=self._check_axis(axis)
        return int(self.query("P"+axis))
    def set_position_reference(self, axis, position=0):
        """
        Set the current axis position as a reference.
        
        Re-calibrate the position encoder so that the current position is set as `position` (0 by default).
        """
        axis=self._check_axis(axis)
        self.query("P{}={:.0f}".format(axis,position))
    def move_to(self, axis, position):
        """Move a given axis to a given position"""
        axis=self._check_axis(axis)
        self.query("{}{:.0f}".format(axis,position))
    def move(self, axis, steps=1):
        """Move a given axis for a given number of steps"""
        self.move_to(axis,self.get_position(axis)+steps)
    def jog(self, axis, direction):
        """
        Jog a given axis in a given direction.
        
        `direction` can be either ``"-"`` (negative) or ``"+"`` (positive).
        The motion continues until it is explicitly stopped, or unitl a limit is hit.
        """
        axis=self._check_axis(axis)
        if not direction: # 0 or False also mean left
            direction="-"
        if direction in [1, True]:
            direction="+"
        if direction not in ["+","-"]:
            raise ArcusError("unrecognized direction: {}".format(direction))
        self.query("J{}{}".format(axis,direction))
    def stop(self, axis):
        """Stop motion of a given axis"""
        axis=self._check_axis(axis)
        self.query("STOP"+axis)
    def stop_all(self):
        """Stop motion of all axes"""
        for axis in "XY":
            self.query("STOP"+axis)

    def get_speed(self):
        """Get the global speed setting (in Hz)"""
        return int(self.query("HSPD"))
    def get_axis_speed(self, axis):
        """Get the individual axis speed setting (in Hz)"""
        axis=self._check_axis(axis)
        return int(self.query("HSPD"+axis))
    def set_speed(self, speed):
        """Set the global speed setting (in Hz)"""
        self.query("HSPD={:.0f}".format(speed))
    def set_axis_speed(self, axis, speed):
        """Set the individual axis speed setting (in Hz)"""
        axis=self._check_axis(axis)
        self.query("HSPD{}={:.0f}".format(axis,speed))

    _status_bits={  "accel":0x001,"decel":0x002,"moving":0x004,
                    "alarm":0x008,
                    "sw_plus_lim":0x010,"sw_minus_lim":0x020,"sw_home":0x040,
                    "err_plus_lim":0x080,"err_minus_lim":0x100,"err_alarm":0x200,
                    "TOC_timeout":0x800}
    def _get_full_status(self):
        return [int(self.query("MST{}".format(axis))) for axis in "XY"]
    def get_status_n(self, axis):
        """Get the axis status as an integer"""
        axis=self._check_axis(axis)
        axis_n="XY".index(axis)
        return self._get_full_status()[axis_n]
    def get_status(self, axis):
        """Get the axis status as a set of string descriptors"""
        statn=self.get_status_n(axis)
        return [ k for k in self._status_bits if self._status_bits[k]&statn ]
    def is_moving(self, axis):
        """Check if a given axis is moving"""
        return bool(self.get_status_n(axis)&0x007)

    def check_limit_error(self, axis):
        """
        Check if the axis hit limit errors.

        Return ``""`` (not errors), ``"+"`` (positive limit error) or ``"-"`` (negative limit error).
        """
        stat=self.get_status_n(axis)
        err=""
        if stat&self._status_bits["err_plus_lim"]:
            err=err+"+"
        if stat&self._status_bits["err_minus_lim"]:
            err=err+"-"
        return err
    def clear_limit_error(self, axis):
        """Clear axis limit errors"""
        axis=self._check_axis(axis)
        self.query("CLR"+axis)
```

**Comment by bws5** [comment]
Thanks Alexey,

That fixed the issue: all the commands that I've tried now work. Thanks for the help!

Ben
